web:
  restart: always
  command: honcho start
  build: .
  links:
    - postgres
    - redis
  env_file: .env_web_prod

nginx:
  restart: always
  build: ./deployment/docker/nginx/
  ports:
    - "80:80"
  links:
    - web:web

postgres:
  restart: always
  image: mdillon/postgis
  volumes_from:
    - data
  ports:
    - "5432:5432"
  env_file: .env_db_prod

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"